<%@ Page Title="" Language="C#" MasterPageFile="~/MasterHome.master" AutoEventWireup="true" CodeFile="ProjectMast.aspx.cs" Inherits="Masters_ProjectMast" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolderhead" runat="Server">
    <style type="text/css">
        .ModGridview {
            font-family: Verdana;
            font-size: 10pt;
            font-weight: normal;
            color: black;
        }

        .modalBackground {
            background-color: Gray;
            filter: alpha(opacity=80);
            opacity: 0.8;
            z-index: 10000;
        }
    </style>
    <script type="text/javascript">
        function closepopup() {
            $find('ModalPopupExtender1').hide();
        }

        function Confirm() {
            var confirm_value = document.createElement("INPUT");
            confirm_value.type = "hidden";
            confirm_value.name = "confirm_value";
            if (confirm("Do You Want To Delete This Entry ? ")) {
                confirm_value.value = "Yes";
            }
            else {
                confirm_value.value = "No";
            }
            document.forms[0].appendChild(confirm_value);
        }

        function validate() {
            var str = "";            
            if (document.getElementById("<%=DDLClientName.ClientID%>").value == "0") {
                str = str + "Select Client. \n";
            }
            if (document.getElementById("<%=TxtPrjName.ClientID%>").value == "") {
                str = str + "Enter Project Name. \n";
            }

            if (str == "") {
                return (true);
            }
            else {
                alert(str);
                return (false);
            }
        }
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolderPage" runat="Server">
    <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server"></asp:ToolkitScriptManager>
    <%-- <asp:RoundedCornersExtender ID="RoundedCornersExtender1" runat="server" TargetControlID="HeadDiv" Radius="50" Corners="All">
    </asp:RoundedCornersExtender>--%>
    <div id="HeadDiv" runat="server" class="content_resize" style="-moz-border-radius: 50px; -webkit-border-radius: 50px; border-radius: 50px;">
        <asp:SiteMapDataSource ID="SiteMapDataSource1" runat="server" />
        <asp:SiteMapPath ID="SiteMap1" runat="server"></asp:SiteMapPath>

        <div class="content">
            <div>
                <%--style="height: 530px"--%>
                <asp:UpdatePanel ID="UpdatePanel2" runat="server">
                    <ContentTemplate>
                        <asp:Menu ID="MyMenu" Width="250px" runat="server" Orientation="Horizontal" StaticEnableDefaultPopOutImage="False"
                            OnMenuItemClick="MyMenu_MenuItemClick" RenderingMode="Table" BorderStyle="None">
                            <Items>
                                <asp:MenuItem ImageUrl="~/images/ViewEnable.jpg" Value="0" Text=" "></asp:MenuItem>
                                <asp:MenuItem ImageUrl="~/images/NewOrEditDisable.jpg" Text=" " Value="1"></asp:MenuItem>
                            </Items>
                        </asp:Menu>
                        <div style="border: 1px solid #C0C0C0;">
                            <asp:MultiView ID="MyMultiView" runat="server" ActiveViewIndex="0">
                                <asp:View ID="TabView" runat="server">
                                    <table>
                                        <tr>
                                            <td>

                                                <asp:Button ID="BtnView" runat="server" Text="View All" CssClass="button black" Height="25px" Width="77px" OnClick="BtnView_Click" />
                                            </td>
                                        </tr>
                                        <tr style="vertical-align: top">
                                            <td>
                                                <%--AutoGenerateDeleteButton="True" OnRowDeleting="GridPrj_RowDeleting"
                                                    AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridPrj_SelectedIndexChanged" --%>
                                                <asp:GridView ID="GridPrj" runat="server"
                                                    AutoGenerateColumns="False"
                                                    DataKeyNames="Id"
                                                    OnPageIndexChanging="GridPrj_PageIndexChanging"
                                                    CssClass="mGrid"
                                                    PageSize="10"
                                                    EmptyDataText="No Data Available">
                                                    <Columns>
                                                        <asp:TemplateField>
                                                            <ItemTemplate>
                                                                <asp:ImageButton ID="imgbtnEdit" runat="server" OnClick="btnPrjSelect_Click" CommandName="Select" AlternateText="Edit" ImageUrl="~/images/Edit.jpg" ToolTip="Edit" Height="20px" Width="20px" />
                                                                <asp:ImageButton ID="imgbtnDelete" runat="server" OnClick="btnPrjDelete_Click" AlternateText="Delete" ImageUrl="~/images/Delete.png" ToolTip="Delete" Height="20px" Width="20px" />
                                                            </ItemTemplate>
                                                        </asp:TemplateField>
                                                        <asp:TemplateField HeaderText="Id" Visible="False">
                                                            <ItemTemplate>
                                                                <asp:Label ID="LblGrdId" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                                                            </ItemTemplate>
                                                            <ItemStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                                                        </asp:TemplateField>
                                                        <asp:TemplateField HeaderText="Client Name">
                                                            <ItemTemplate>
                                                                <asp:Label ID="LblGrdClientName" runat="server" Width="200px" Text='<%# Bind("ClientName") %>'></asp:Label>
                                                            </ItemTemplate>
                                                            <EditItemTemplate>
                                                                <asp:TextBox ID="TxtGrdClientName" runat="server" Width="200px" BorderStyle="None" Text='<%# Bind("ClientName") %>'></asp:TextBox>
                                                            </EditItemTemplate>
                                                            <ItemStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                                                        </asp:TemplateField>
                                                        <asp:TemplateField HeaderText="Project Name">
                                                            <ItemTemplate>
                                                                <asp:Label ID="LblGrdPrjName" runat="server" Width="200px" Text='<%# Bind("ProjectName") %>'></asp:Label>
                                                            </ItemTemplate>
                                                            <EditItemTemplate>
                                                                <asp:TextBox ID="TxtGrdPrjName" runat="server" Width="200px" BorderStyle="None" Text='<%# Bind("ProjectName") %>'></asp:TextBox>
                                                            </EditItemTemplate>
                                                            <ItemStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                                                        </asp:TemplateField>
                                                        <asp:TemplateField HeaderText="Project Status">
                                                            <ItemTemplate>
                                                                <asp:Label ID="LblGrdPrjStatus" runat="server" Width="150px" Text='<%# Bind("ProjctStatus") %>'></asp:Label>
                                                            </ItemTemplate>
                                                            <EditItemTemplate>
                                                                <asp:TextBox ID="TxtGrdPrjStatus" runat="server" Width="150px" BorderStyle="None" Text='<%# Bind("ProjctStatus") %>'></asp:TextBox>
                                                            </EditItemTemplate>
                                                            <ItemStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                                                        </asp:TemplateField>
                                                    </Columns>
                                                </asp:GridView>
                                                <asp:Button ID="btnShowPopup" runat="server" Style="display: none" />
                                                <asp:ModalPopupExtender ID="ModalPopupExtender1" runat="server" TargetControlID="btnShowPopup" PopupControlID="pnlpopup"
                                                    CancelControlID="btnno" BackgroundCssClass="modalBackground">
                                                </asp:ModalPopupExtender>
                                                <asp:Panel ID="pnlpopup" runat="server" BackColor="White" Height="130px" Width="400px" Style="display: none;">
                                                    <table style="border: Solid 2px #D46900; width: 100%; height: 100%">
                                                        <tr style="background-image: url('../images/header-js.gif')">
                                                            <td style="height: 10%; color: White; font-weight: bold; padding: 3px; font-size: larger; font-family: Calibri; text-align: left;">Confirm Box
                                                            </td>
                                                            <td style="color: White; font-weight: bold; padding: 3px; font-size: larger; text-align: right;">
                                                                <a href="javascript:void(0)" onclick="closepopup()">
                                                                    <img src="../images/Close-js.gif" style="border: 0px; text-align: right;" /></a>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td colspan="2" style="text-align: left; padding: 5px; font-family: Calibri">
                                                                <asp:Label ID="lblUser" runat="server" />
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td colspan="2"></td>
                                                        </tr>
                                                        <tr>
                                                            <td></td>
                                                            <td style="text-align: right; padding-right: 15px">
                                                                <asp:ImageButton ID="btnYes" OnClick="btnYes_Click" runat="server" ImageUrl="~/images/btnyes-js.jpg" />
                                                                <asp:ImageButton ID="btnNo" runat="server" ImageUrl="~/images/btnNo-js.jpg" />
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </asp:Panel>
                                            </td>
                                        </tr>
                                    </table>
                                </asp:View>

                                <asp:View ID="TabNewEdit" runat="server">
                                    <table>
                                        <tr style="vertical-align: top">
                                            <th></th>
                                            <td style="text-align: left;">
                                                <asp:HiddenField ID="HidFldId" runat="server" />
                                            </td>
                                            <td>
                                                <asp:HiddenField ID="HidFldUID" runat="server" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <th></th>
                                            <td colspan="2" style="vertical-align: top">
                                                <asp:Label ID="LblMsg" runat="server" Text="..." Font-Bold="True" Font-Size="Small" ForeColor="Red"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr style="vertical-align: top">
                                            <th style="text-align: left; color: #FF0000;">*</th>
                                            <th style="text-align: left;">Client Name</th>
                                            <td style="text-align: left;">
                                                <asp:DropDownList ID="DDLClientName" runat="server" Width="331px">
                                                </asp:DropDownList>
                                            </td>
                                        </tr>
                                        <tr style="vertical-align: top">
                                            <th style="text-align: left; color: #FF0000;">*</th>
                                            <th style="text-align: left;">Project Name</th>
                                            <td style="text-align: left;">
                                                <asp:TextBox ID="TxtPrjName" runat="server" Width="325px" Style="margin-bottom: 0px"></asp:TextBox>
                                            </td>
                                        </tr>
                                        <tr style="vertical-align: top">
                                            <th></th>
                                            <th style="text-align: left;">Start Date</th>
                                            <td style="text-align: left;">
                                                <asp:TextBox ID="TxtStartDate" runat="server" Width="100px"></asp:TextBox>
                                                <asp:ImageButton ID="imgbtnCalendar2" runat="server" ImageUrl="~/images/date_picker1.gif" Height="20px" Width="20px" />
                                                <asp:CalendarExtender ID="CalendarExtender2" runat="server" Format="dd/MM/yyyy"
                                                    PopupButtonID="imgbtnCalendar2" PopupPosition="BottomRight" TargetControlID="TxtStartDate" Enabled="True">
                                                </asp:CalendarExtender>
                                            </td>
                                        </tr>
                                        <tr style="vertical-align: top">
                                            <th></th>
                                            <th style="text-align: left;">End Date</th>
                                            <td style="text-align: left;">
                                                <asp:TextBox ID="TxtEndDate" runat="server" Width="100px"></asp:TextBox>
                                                <asp:ImageButton ID="imgbtnCalendar" runat="server" ImageUrl="~/images/date_picker1.gif" Height="20px" Width="20px" />
                                                <asp:CalendarExtender ID="CalendarExtender1" runat="server" Format="dd/MM/yyyy"
                                                    PopupButtonID="imgbtnCalendar" PopupPosition="BottomRight" TargetControlID="TxtEndDate" Enabled="True">
                                                </asp:CalendarExtender>
                                            </td>
                                        </tr>
                                        <tr style="vertical-align: top">
                                            <th></th>
                                            <th style="text-align: left;">Project Status</th>
                                            <td style="text-align: left;">
                                                <asp:DropDownList ID="ddlPrjStatus" runat="server" Width="150px">
                                                    <asp:ListItem Value="0">---Select Status---</asp:ListItem>
                                                    <asp:ListItem Value="D">Done</asp:ListItem>
                                                    <asp:ListItem Value="P">Pending</asp:ListItem>
                                                </asp:DropDownList>
                                            </td>
                                        </tr>
                                        <tr style="vertical-align: top">
                                            <th></th>
                                            <th style="text-align: left;">Remark</th>
                                            <td style="text-align: left;">
                                                <asp:TextBox ID="TxtRemark" runat="server" Width="283px" TextMode="MultiLine" Height="55px"></asp:TextBox>
                                            </td>
                                        </tr>
                                        <tr style="text-align: left;">
                                             <th></th>
                                            <%--<td style="text-align: left;"></td>--%>
                                            <td colspan="2" style="text-align: left;">
                                                <%-- <asp:Button ID="BtnModuleList" runat="server" Text="Add Module" OnClientClick="return ShowPanel()" CssClass="buttonclass" />--%>
                                                <%--EmptyDataText="No Data Available" --%>
                                                <asp:Panel ID="ModulePanel" runat="server" ScrollBars="Auto" Width="900px">
                                                    <asp:GridView ID="GridModule" runat="server"
                                                        DataKeyNames="Id,ProjectId"
                                                        AutoGenerateColumns="false" HeaderStyle-BackColor="#61A6F8"
                                                        ShowFooter="true" HeaderStyle-Font-Bold="true" HeaderStyle-ForeColor="White"
                                                        OnRowCancelingEdit="GridModule_RowCancelingEdit"
                                                        OnRowEditing="GridModule_RowEditing"
                                                        OnRowUpdating="GridModule_RowUpdating"
                                                        OnRowCommand="GridModule_RowCommand"
                                                        OnRowDeleting="GridModule_RowDeleting"
                                                        CssClass="ModGridview"
                                                        PageSize="10">

                                                        <Columns>
                                                            <asp:TemplateField HeaderText="Id" Visible="false">
                                                                <EditItemTemplate>
                                                                    <asp:Label ID="LblEditId" runat="server" Text='<%#Eval("Id") %>' />
                                                                </EditItemTemplate>
                                                                <ItemTemplate>
                                                                    <asp:Label ID="LblItmId" runat="server" Text='<%#Eval("Id") %>' />
                                                                </ItemTemplate>
                                                                <FooterTemplate>
                                                                    <asp:Label ID="LblFtrId" runat="server" />
                                                                </FooterTemplate>
                                                            </asp:TemplateField>
                                                            <asp:TemplateField HeaderText="Project Id" Visible="false">
                                                                <EditItemTemplate>
                                                                    <asp:Label ID="LblEditPrjId" runat="server" Text='<%#Eval("ProjectId") %>' />
                                                                </EditItemTemplate>
                                                                <ItemTemplate>
                                                                    <asp:Label ID="LblItmPrjId" runat="server" Text='<%#Eval("ProjectId") %>' />
                                                                </ItemTemplate>
                                                                <FooterTemplate>
                                                                    <asp:Label ID="LblFtrPrjId" runat="server" />
                                                                </FooterTemplate>
                                                            </asp:TemplateField>

                                                            <asp:TemplateField HeaderText="Module Name">
                                                                <EditItemTemplate>
                                                                    <asp:TextBox ID="TxtEditModName" runat="server" Text='<%#Eval("ModuleName") %>' />
                                                                </EditItemTemplate>
                                                                <ItemTemplate>
                                                                    <asp:Label ID="LblItmModName" runat="server" Text='<%#Eval("ModuleName") %>' />
                                                                </ItemTemplate>
                                                                <FooterTemplate>
                                                                    <asp:TextBox ID="TxtFtrModName" runat="server" />
                                                                    <asp:RequiredFieldValidator ID="RFvModName" runat="server" ControlToValidate="TxtFtrModName" Text="*" ValidationGroup="validaiton" />
                                                                </FooterTemplate>
                                                            </asp:TemplateField>

                                                            <asp:TemplateField HeaderText="Start Date">
                                                                <EditItemTemplate>
                                                                    <asp:TextBox ID="TxtEditStartDate" runat="server" Width="100px" Text='<%#Eval("StartDate") %>' />
                                                                    <asp:ImageButton ID="imgbtnCalendar1" runat="server" ImageUrl="~/images/date_picker1.gif" Height="20px" Width="20px" />
                                                                    <asp:CalendarExtender ID="CalendarExtender1" runat="server" Format="dd/MM/yyyy"
                                                                        PopupButtonID="imgbtnCalendar1" PopupPosition="BottomRight" TargetControlID="TxtEditStartDate" Enabled="True">
                                                                    </asp:CalendarExtender>
                                                                </EditItemTemplate>
                                                                <ItemTemplate>
                                                                    <asp:Label ID="LblItmStartDate" runat="server" Text='<%#Eval("StartDate") %>' />
                                                                </ItemTemplate>
                                                                <FooterTemplate>
                                                                    <asp:TextBox ID="TxtFtrStartDate" runat="server" Width="100px" />
                                                                    <asp:ImageButton ID="imgbtnCalendar2" runat="server" ImageUrl="~/images/date_picker1.gif" Height="20px" Width="20px" />
                                                                    <asp:CalendarExtender ID="CalendarExtender2" runat="server" Format="dd/MM/yyyy"
                                                                        PopupButtonID="imgbtnCalendar2" PopupPosition="BottomRight" TargetControlID="TxtFtrStartDate" Enabled="True">
                                                                    </asp:CalendarExtender>
                                                                    <asp:RequiredFieldValidator ID="RFvStartDate" runat="server" ControlToValidate="TxtFtrStartDate" Text="*" ValidationGroup="validaiton" />
                                                                </FooterTemplate>
                                                            </asp:TemplateField>

                                                            <asp:TemplateField HeaderText="End Date">
                                                                <EditItemTemplate>
                                                                    <asp:TextBox ID="TxtEditEndDate" runat="server" Width="100px" Text='<%#Eval("EndDate") %>' />
                                                                    <asp:ImageButton ID="imgbtnCalendar3" runat="server" ImageUrl="~/images/date_picker1.gif" Height="20px" Width="20px" />
                                                                    <asp:CalendarExtender ID="CalendarExtender3" runat="server" Format="dd/MM/yyyy"
                                                                        PopupButtonID="imgbtnCalendar3" PopupPosition="BottomRight" TargetControlID="TxtEditEndDate" Enabled="True">
                                                                    </asp:CalendarExtender>
                                                                </EditItemTemplate>
                                                                <ItemTemplate>
                                                                    <asp:Label ID="LblItmEndDate" runat="server" Text='<%#Eval("EndDate") %>' />
                                                                </ItemTemplate>
                                                                <FooterTemplate>
                                                                    <asp:TextBox ID="TxtFtrEndDate" runat="server" Width="100px" />
                                                                    <asp:ImageButton ID="imgbtnCalendar4" runat="server" ImageUrl="~/images/date_picker1.gif" Height="20px" Width="20px" />
                                                                    <asp:CalendarExtender ID="CalendarExtender4" runat="server" Format="dd/MM/yyyy"
                                                                        PopupButtonID="imgbtnCalendar4" PopupPosition="BottomRight" TargetControlID="TxtFtrEndDate" Enabled="True">
                                                                    </asp:CalendarExtender>
                                                                </FooterTemplate>
                                                            </asp:TemplateField>

                                                            <asp:TemplateField HeaderText="Module Status">
                                                                <EditItemTemplate>
                                                                    <asp:DropDownList ID="DDlEditModStat" runat="server" Height="26px" Width="100px">
                                                                        <asp:ListItem Value="0">---Select---</asp:ListItem>
                                                                        <asp:ListItem Value="D">Done</asp:ListItem>
                                                                        <asp:ListItem Value="P">Pending</asp:ListItem>
                                                                        <asp:ListItem Value="C">Cancel</asp:ListItem>
                                                                    </asp:DropDownList>
                                                                </EditItemTemplate>
                                                                <ItemTemplate>
                                                                    <asp:Label ID="LblItmModStat" runat="server" Text='<%#Eval("ModuleStatus") %>' />
                                                                </ItemTemplate>
                                                                <FooterTemplate>
                                                                    <asp:DropDownList ID="DDlFtrModStat" runat="server" Height="26px" Width="100px">
                                                                        <asp:ListItem Value="0">---Select---</asp:ListItem>
                                                                        <asp:ListItem Value="D">Done</asp:ListItem>
                                                                        <asp:ListItem Value="P">Pending</asp:ListItem>
                                                                        <asp:ListItem Value="C">Cancel</asp:ListItem>
                                                                    </asp:DropDownList>
                                                                    <asp:RequiredFieldValidator ID="RFvModStat" runat="server" ControlToValidate="DDlFtrModStat" Text="*" ValidationGroup="validaiton" />
                                                                </FooterTemplate>
                                                            </asp:TemplateField>

                                                            <asp:TemplateField HeaderText="Remark">
                                                                <EditItemTemplate>
                                                                    <asp:TextBox ID="TxtEditRemark" runat="server" Width="150px" Text='<%#Eval("Remark") %>' />
                                                                </EditItemTemplate>
                                                                <ItemTemplate>
                                                                    <asp:Label ID="LblItmRemark" runat="server" Text='<%#Eval("Remark") %>' />
                                                                </ItemTemplate>
                                                                <FooterTemplate>
                                                                    <asp:TextBox ID="TxtFtrRemark" runat="server" Width="150px" />
                                                                </FooterTemplate>
                                                            </asp:TemplateField>

                                                            <asp:TemplateField>
                                                                <EditItemTemplate>
                                                                    <asp:ImageButton ID="imgbtnUpdate" CommandName="Update" runat="server" ImageUrl="~/images/update.jpg" ToolTip="Update" Height="20px" Width="20px" />
                                                                    <asp:ImageButton ID="imgbtnCancel" runat="server" CommandName="Cancel" ImageUrl="~/images/cancel.jpg" ToolTip="Cancel" Height="20px" Width="20px" />
                                                                </EditItemTemplate>
                                                                <ItemTemplate>
                                                                    <asp:ImageButton ID="imgbtnEdit" CommandName="Edit" runat="server" ImageUrl="~/images/Edit.jpg" ToolTip="Edit" Height="20px" Width="20px" />
                                                                    <asp:ImageButton ID="imgbtnDelete" CommandName="Delete" AlternateText="Edit" runat="server"
                                                                        ImageUrl="~/images/Delete-js.png" ToolTip="Delete" Height="20px" Width="20px" /><%--OnClick="btnModDelete_Click"--%>
                                                                </ItemTemplate>
                                                                <FooterTemplate>
                                                                    <asp:ImageButton ID="imgbtnAdd" runat="server" ImageUrl="~/images/AddNewitem.jpg" CommandName="AddNew" Width="30px" Height="30px" ToolTip="Add New Entry" ValidationGroup="validaiton" />
                                                                </FooterTemplate>
                                                            </asp:TemplateField>
                                                        </Columns>
                                                    </asp:GridView>
                                                </asp:Panel>
                                            </td>
                                        </tr>
                                        <tr style="vertical-align: top">
                                            <th></th>
                                            <td style="text-align: left;"></td>
                                            <td style="text-align: left;">
                                                <asp:Button ID="BtnSave" runat="server" Text="Save" CssClass="button black" Height="25px" Width="77px" OnClick="BtnSave_Click" OnClientClick="return validate();"  />
                                                &nbsp;&nbsp;<asp:Button ID="BtnNew" runat="server" Text="New" CssClass="button black" Height="25px" Width="77px" OnClick="BtnNew_Click" />
                                                &nbsp;&nbsp;<asp:Button ID="BtnCancel" runat="server" Text="Cancel" CssClass="button black" Height="25px" Width="77px" OnClick="BtnCancel_Click" />
                                                &nbsp;&nbsp;<asp:Button ID="BtnDelete" runat="server" Text="Delete" CssClass="button black" Height="25px" Width="77px" OnClick="BtnDelete_Click" OnClientClick="Confirm()" />
                                            </td>
                                        </tr>
                                        <tr runat="server" id="trNavigation" style="vertical-align: top">                                            
                                           <th></th>
                                            <td style="text-align: left;"></td>
                                            <td style="text-align: left;">
                                                <asp:ImageButton ID="ImgBtnFirst" runat="server" Height="40px" Width="50px" AlternateText="<" ToolTip="First" ImageAlign="Middle" OnClick="ImgBtnFirst_Click" ImageUrl="~/images/FirstG.png" BorderColor="#00CC00" BorderStyle="Double" />
                                                &nbsp;&nbsp;<asp:ImageButton ID="ImgBtnPrev" runat="server" Height="40px" Width="50px" AlternateText="<<" ToolTip="Prev" ImageAlign="Middle" OnClick="ImgBtnPrev_Click" ImageUrl="~/images/PrevG.png" BorderColor="#00CC00" BorderStyle="Double" />
                                                &nbsp;&nbsp;<asp:ImageButton ID="ImgBtnNext" runat="server" Height="40px" Width="50px" AlternateText=">>" ToolTip="Next" ImageAlign="Middle" OnClick="ImgBtnNext_Click" ImageUrl="~/images/NextG.png" BorderColor="#00CC00" BorderStyle="Double" />
                                                &nbsp;&nbsp;<asp:ImageButton ID="ImgBtnLast" runat="server" Height="40px" Width="50px" AlternateText=">" ToolTip="Last" ImageAlign="Middle" OnClick="ImgBtnLast_Click" ImageUrl="~/images/LastG.png" BorderColor="#00CC00" BorderStyle="Double" />
                                            </td>
                                        </tr>
                                    </table>
                                </asp:View>
                            </asp:MultiView>
                        </div>
                    </ContentTemplate>
                    <Triggers>
                        <asp:AsyncPostBackTrigger ControlID="BtnSave" EventName="Click" />
                        <asp:AsyncPostBackTrigger ControlID="BtnNew" EventName="Click" />
                        <asp:AsyncPostBackTrigger ControlID="BtnCancel" EventName="Click" />
                        <asp:AsyncPostBackTrigger ControlID="BtnDelete" EventName="Click" />
                    </Triggers>
                </asp:UpdatePanel>
            </div>


        </div>
    </div>
</asp:Content>

