<%@ Page Title="" Language="C#" MasterPageFile="~/MasterHome.master" AutoEventWireup="true" CodeFile="ComapnyMast.aspx.cs" Inherits="Masters_ComapnyMast" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolderhead" runat="Server">
    <style type="text/css">
        .fancy-green {
        }
    </style>

     <script type="text/javascript">
         function EMailValidation(fieldName) {
             var str = "";
             if (fieldName.value != "") {
                 var em = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
                 if (!fieldName.value.match(em)) {
                     alert("Enter EMail In Correct Format !!!");
                     document.getElementById("<%=TxtEMailId.ClientID%>").focus();
                        return false;
                    }
                    else {
                        return true;
                    }
                }
         }

         function validate() {

             var str = "";
            if (document.getElementById("<%=TxtCompName.ClientID%>").value == "") {
                str = str + "Company Name Is Blank, Enter Valid Company Name. \n";
              }
              if (document.getElementById("<%=TxtStartDate.ClientID%>").value == "") {
                  str = str + "Start Date Is Blank, Enter Valid Start Date. \n";
              }
              if (document.getElementById("<%=TxtMobNo.ClientID%>").value == "0") {
                  str = str + "Mob.No Is Blank, Enter Valid Mob.No. \n";
              }
              if (document.getElementById("<%=TxtEMailId.ClientID%>").value == "") {
                  str = str + "Email Id Is Blank, Enter Valid Email Id. \n";
              }
              if (str == "") {
                  return (true);
              }
              else {
                  alert(str);
                  return (false);
              }
          }
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolderPage" runat="Server">
    <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server"></asp:ToolkitScriptManager>
    <%-- <asp:RoundedCornersExtender ID="RoundedCornersExtender1" runat="server" TargetControlID="HeadDiv" Radius="50" Corners="All">
     </asp:RoundedCornersExtender>--%>
    <div id="HeadDiv" runat="server" class="content_resize" style="-moz-border-radius: 50px; -webkit-border-radius: 50px; border-radius: 50px;">
        <asp:SiteMapDataSource ID="SiteMapDataSource1" runat="server" />
        <asp:SiteMapPath ID="SiteMap1" runat="server"></asp:SiteMapPath>

        <div class="content">
            <div>
                <table>
                    <tr>
                        <td>
                            <asp:Label ID="LblMsg" runat="server" Text="..." Font-Bold="True" Font-Size="Small" ForeColor="#0000CC"></asp:Label>
                        </td>
                    </tr>
                </table>
            </div>

            <asp:UpdatePanel ID="UpdatePanel2" runat="server">
                <ContentTemplate>
                    <asp:Menu ID="MyMenu" Width="250px" runat="server" Orientation="Horizontal" StaticEnableDefaultPopOutImage="False"
                        OnMenuItemClick="MyMenu_MenuItemClick" RenderingMode="Table" BorderStyle="None">
                        <Items>
                            <asp:MenuItem ImageUrl="~/images/ViewEnable.jpg" Value="0" Text=" "></asp:MenuItem>
                            <asp:MenuItem ImageUrl="~/images/NewOrEditDisable.jpg" Text=" " Value="1"></asp:MenuItem>
                        </Items>
                    </asp:Menu>
                    <div style="border: 1px solid #C0C0C0;">
                        <asp:MultiView ID="MyMultiView" runat="server" ActiveViewIndex="0">
                            <asp:View ID="TabView" runat="server">
                                <table style="text-align: center;">
                                    <tr style="text-align: left;">
                                        <td>

                                            <asp:Button ID="BtnView" runat="server" Text="View All" CssClass="button black" Height="25px" Width="77px" OnClick="BtnView_Click" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <asp:GridView ID="GridComp" runat="server"
                                                AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" DataKeyNames="Id"
                                                OnPageIndexChanging="GridComp_PageIndexChanging"
                                                OnRowDeleting="GridComp_RowDeleting"
                                                OnSelectedIndexChanged="GridComp_SelectedIndexChanged"
                                                CssClass="mGrid">
                                                <Columns>
                                                    <asp:TemplateField HeaderText="Id" Visible="False">
                                                        <ItemTemplate>
                                                            <asp:Label ID="LblGrdId" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                                                        </ItemTemplate>
                                                        <ItemStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                                                    </asp:TemplateField>
                                                    <asp:TemplateField HeaderText="Company Name">
                                                        <ItemTemplate>
                                                            <asp:Label ID="LblGrdCompName" runat="server" Width="200px" Text='<%# Bind("CompName") %>'></asp:Label>
                                                        </ItemTemplate>
                                                        <EditItemTemplate>
                                                            <asp:TextBox ID="TxtGrdCompName" runat="server" Width="200px" BorderStyle="None" Text='<%# Bind("CompName") %>'></asp:TextBox>
                                                        </EditItemTemplate>
                                                        <ItemStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                                                    </asp:TemplateField>
                                                    <asp:TemplateField HeaderText="WebSite">
                                                        <ItemTemplate>
                                                            <asp:Label ID="LblGrdWebSite" runat="server" Width="150px" Text='<%# Bind("WebSite") %>'></asp:Label>
                                                        </ItemTemplate>
                                                        <EditItemTemplate>
                                                            <asp:TextBox ID="TxtGrdWebSite" runat="server" Width="150px" BorderStyle="None" Text='<%# Bind("WebSite") %>'></asp:TextBox>
                                                        </EditItemTemplate>
                                                        <ItemStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                                                    </asp:TemplateField>
                                                    <asp:TemplateField HeaderText="Mobile No">
                                                        <ItemTemplate>
                                                            <asp:Label ID="LblGrdMobNo" runat="server" Width="110px" Text='<%# Bind("MobNo") %>'></asp:Label>
                                                        </ItemTemplate>
                                                        <EditItemTemplate>
                                                            <asp:TextBox ID="TxtGrdMobNo" runat="server" Width="110px" BorderStyle="None" Text='<%# Bind("MobNo") %>'></asp:TextBox>
                                                        </EditItemTemplate>
                                                        <ItemStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                                                    </asp:TemplateField>
                                                    <asp:TemplateField HeaderText="State">
                                                        <ItemTemplate>
                                                            <asp:Label ID="LblGrdStateName" runat="server" Width="120px" Text='<%# Bind("StateName") %>'></asp:Label>
                                                        </ItemTemplate>
                                                        <EditItemTemplate>
                                                            <asp:TextBox ID="TxtGrdStateName" runat="server" Width="120px" BorderStyle="None" Text='<%# Bind("StateName") %>'></asp:TextBox>
                                                        </EditItemTemplate>
                                                        <ItemStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                                                    </asp:TemplateField>
                                                    <asp:TemplateField HeaderText="City">
                                                        <ItemTemplate>
                                                            <asp:Label ID="LblGrdCityName" runat="server" Width="120px" Text='<%# Bind("CityName") %>'></asp:Label>
                                                        </ItemTemplate>
                                                        <EditItemTemplate>
                                                            <asp:TextBox ID="TxtGrdCityName" runat="server" Width="120px" BorderStyle="None" Text='<%# Bind("CityName") %>'></asp:TextBox>
                                                        </EditItemTemplate>
                                                        <ItemStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                                                    </asp:TemplateField>
                                                </Columns>
                                            </asp:GridView>
                                        </td>
                                    </tr>
                                </table>

                            </asp:View>
                            <asp:View ID="TabNewEdit" runat="server">
                                <table style="text-align: center;">
                                    <tr>
                                        <td colspan="3" style="text-align: left;">
                                            <asp:HiddenField ID="HidFldId" runat="server" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="3">
                                            <asp:HiddenField ID="HidFldUID" runat="server" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <th style="text-align: left; color: #FF0000;">*</th>
                                        <th style="text-align: left;">Company Name</th>
                                        <td style="text-align: left;">
                                            <asp:TextBox ID="TxtCompName" runat="server" Width="475px"></asp:TextBox>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th style="text-align: left; color: #FF0000;">*</th>
                                        <th style="text-align: left;">Start Date</th>
                                        <td style="text-align: left;">
                                            <asp:TextBox ID="TxtStartDate" runat="server"></asp:TextBox>
                                            <asp:ImageButton ID="imgbtnCalendar" runat="server" ImageUrl="~/images/date_picker1.gif" Height="20px" Width="20px" />
                                            <asp:CalendarExtender ID="CalendarExtender1" runat="server" Format="dd/MM/yyyy"
                                                PopupButtonID="imgbtnCalendar" PopupPosition="BottomRight" TargetControlID="TxtStartDate" Enabled="True">
                                            </asp:CalendarExtender>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th></th>
                                        <th style="text-align: left;">Country</th>
                                        <td style="text-align: left;">
                                            <asp:DropDownList ID="ddlCountry" runat="server" Width="300px" OnSelectedIndexChanged="ddlCountry_SelectedIndexChanged" AutoPostBack="true"></asp:DropDownList>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th></th>
                                        <th style="text-align: left;">State</th>
                                        <td style="text-align: left;">
                                            <asp:DropDownList ID="ddlState" runat="server" Width="300px" OnSelectedIndexChanged="ddlState_SelectedIndexChanged" AutoPostBack="true"></asp:DropDownList>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th></th>
                                        <th style="text-align: left;">City</th>
                                        <td style="text-align: left;">
                                            <asp:DropDownList ID="ddlCity" runat="server" Width="300px"></asp:DropDownList>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th></th>
                                        <th style="text-align: left;">Address 1</th>
                                        <td style="text-align: left;">
                                            <asp:TextBox ID="TxtAddress1" runat="server" Width="425px" TextMode="MultiLine"></asp:TextBox>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th></th>
                                        <th style="text-align: left;">Pin Code</th>
                                        <td style="text-align: left;">
                                            <asp:TextBox ID="TxtPinCode" runat="server" Width="145px"></asp:TextBox>
                                        </td>
                                    </tr>



                                    <tr>
                                        <th style="text-align: left; color: #FF0000;">*</th>
                                        <th style="text-align: left;">Mobile Number</th>
                                        <td style="text-align: left;">
                                            <asp:TextBox ID="TxtMobNo" runat="server" Width="200px"></asp:TextBox>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th></th>
                                        <th style="text-align: left;">Phone Number</th>
                                        <td style="text-align: left;">
                                            <asp:TextBox ID="TxtPhone" runat="server" Width="200px"></asp:TextBox>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th style="text-align: left; color: #FF0000;">*</th>
                                        <th style="text-align: left;">EMail Id</th>
                                        <td style="text-align: left;">
                                            <asp:TextBox ID="TxtEMailId" runat="server" Width="415px" onblur="EMailValidation(this);"></asp:TextBox>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th style="text-align: left; color: #FF0000;">*</th>
                                        <th style="text-align: left;">WebSite</th>
                                        <td style="text-align: left;">
                                            <asp:TextBox ID="TxtWebSite" runat="server" Width="415px"></asp:TextBox>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" style="text-align: center;">
                                            <asp:Button ID="BtnSave" runat="server" Text="Save" CssClass="button black" Height="25px" Width="77px" OnClick="BtnSave_Click" OnClientClick="return validate();"  />
                                            &nbsp;&nbsp;<asp:Button ID="BtnNew" runat="server" Text="New" CssClass="button black" Height="25px" Width="77px" OnClick="BtnNew_Click" />
                                            &nbsp;&nbsp;<asp:Button ID="BtnCancel" runat="server" Text="Cancel" CssClass="button black" Height="25px" Width="77px" OnClick="BtnCancel_Click" />
                                            &nbsp;&nbsp;<asp:Button ID="BtnDelete" runat="server" Text="Delete" CssClass="button black" Height="25px" Width="77px" OnClick="BtnDelete_Click" /></td>
                                    </tr>
                                    <tr runat="server" id="trNavigation" style="vertical-align: top">
                                        <td colspan="3" style="text-align: left;">
                                            <asp:ImageButton ID="ImgBtnFirst" runat="server" Height="40px" Width="50px" AlternateText="<" ToolTip="First" ImageAlign="Middle" OnClick="ImgBtnFirst_Click" ImageUrl="~/images/FirstG.png" BorderColor="#00CC00" BorderStyle="Double" />
                                            &nbsp;&nbsp;<asp:ImageButton ID="ImgBtnPrev" runat="server" Height="40px" Width="50px" AlternateText="<<" ToolTip="Prev" ImageAlign="Middle" OnClick="ImgBtnPrev_Click" ImageUrl="~/images/PrevG.png" BorderColor="#00CC00" BorderStyle="Double" />
                                            &nbsp;&nbsp;<asp:ImageButton ID="ImgBtnNext" runat="server" Height="40px" Width="50px" AlternateText=">>" ToolTip="Next" ImageAlign="Middle" OnClick="ImgBtnNext_Click" ImageUrl="~/images/NextG.png" BorderColor="#00CC00" BorderStyle="Double" />
                                            &nbsp;&nbsp;<asp:ImageButton ID="ImgBtnLast" runat="server" Height="40px" Width="50px" AlternateText=">" ToolTip="Last" ImageAlign="Middle" OnClick="ImgBtnLast_Click" ImageUrl="~/images/LastG.png" BorderColor="#00CC00" BorderStyle="Double" />
                                        </td>
                                    </tr>
                                </table>

                            </asp:View>
                        </asp:MultiView>
                    </div>
                </ContentTemplate>
            </asp:UpdatePanel>
        </div>
    </div>

    <%--<div class="content_resize">
         <asp:SiteMapDataSource ID="SiteMapDataSource1" runat="server" />
        <asp:SiteMapPath ID="SiteMap1" runat="server"></asp:SiteMapPath>
        <div class="article">
            <h2>Companys Details</h2>
        </div>
        <div class="article">
            <table>
                <tr>
                    <td colspan="2" style="text-align: left;">
                        <asp:HiddenField ID="HidFldId" runat="server" />
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;" class="auto-style1">Company Name</th>
                    <td style="text-align: left;">
                        <asp:TextBox ID="TxtCompName" runat="server" MaxLength="50" Text="" Width="250px"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldCompName" runat="server" ErrorMessage="*" ControlToValidate="TxtCompName" ForeColor="#FF3300"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;" class="auto-style1">Address 1</th>
                    <td style="text-align: left;">
                        <asp:TextBox ID="TxtAddress1" runat="server" MaxLength="100" Text="" Width="325px"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;" class="auto-style1">Address 2</th>
                    <td style="text-align: left;">
                        <asp:TextBox ID="TxtAddress2" runat="server" MaxLength="100" Text="" Width="325px"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;" class="auto-style1">Address 3</th>
                    <td style="text-align: left;">
                        <asp:TextBox ID="TxtAddress3" runat="server" MaxLength="100" Text="" Width="325px"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;" class="auto-style1">Pin Code</th>
                    <td style="text-align: left;">
                        <asp:TextBox ID="TxtPinCode" runat="server" MaxLength="25" Text="" Width="150px"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;">City</th>
                    <td>
                        <asp:DropDownList ID="DDLCity" runat="server" Height="17px" Width="249px"></asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;">State</th>
                    <td>
                        <asp:DropDownList ID="DDLState" runat="server" Height="17px" Width="249px"></asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;">Country</th>
                    <td>
                        <asp:DropDownList ID="DDLCountry" runat="server" Height="18px" Width="249px"></asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;" class="auto-style1">WebSite</th>
                    <td style="text-align: left;">
                        <asp:TextBox ID="TxtWebSite" runat="server" MaxLength="50" Width="250px"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;" class="auto-style1">EMail Id</th>
                    <td style="text-align: left;">
                        <asp:TextBox ID="TxtEMailId" runat="server" MaxLength="50" Width="261px"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldEMailId" runat="server" ErrorMessage="*" ControlToValidate="TxtEMailId" ForeColor="#FF3300"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;" class="auto-style1">Mobile Number</th>
                    <td style="text-align: left;">
                        <asp:TextBox ID="TxtMobNo" runat="server" MaxLength="15" Width="200px"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;" class="auto-style1">Contact No.1</th>
                    <td style="text-align: left;">
                        <asp:TextBox ID="TxtContact1" runat="server" MaxLength="15" Width="200px"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: left;" class="auto-style1">Contact No.2</th>
                    <td style="text-align: left;">
                        <asp:TextBox ID="TxtContact2" runat="server" MaxLength="15" Width="200px"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: center;">
                        <asp:Button ID="BtnSave" runat="server" Text="Save" CssClass="buttonclass" Width="77px" /></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <asp:GridView ID="GridComp" runat="server"></asp:GridView>
                    </td>
                </tr>
            </table>
        </div>
    </div>--%>
</asp:Content>

